import type { NextPage } from 'next'
import Head from 'next/head'
import WalletConnect from '../components/WalletConnect'
import { useStoreActions, useStoreState } from "../utils/store"
import Link from 'next/link'
import { useState, useEffect } from 'react'
import { getAssets } from "../utils/cardano";
import initLucid from '../utils/lucid'
import { Lucid } from 'lucid-cardano'

const Home: NextPage = () => {
  const walletStore = useStoreState((state: any) => state.wallet)
  const [nftList, setNftList] = useState([])
  const [lucid, setLucid] = useState<Lucid>()

  useEffect(() => {
    //const lucid = initLucid(walletStore.name)
    if (walletStore.address != "") {
      getAssets(walletStore.address)
        .then((res: any) => { setNftList(res.addressInfo.nfts) })
      if (lucid) {
        console.log("useEffect was called")
      } else {
        initLucid(walletStore.name).then((Lucid: Lucid) => { setLucid(Lucid) });
      }
    }
  }, [lucid, walletStore.address])

  const checkIsConnected = async () => {
    alert("check connection");
  }

  return (
    <div className="px-10">
      <Head>
        <title>Decentralized Stablecoin dUSD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="navbar bg-base-100">
        <div className="navbar-start">
          <div className="dropdown">
            <div tabIndex={0} role="button" className="btn btn-ghost btn-circle">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h7" /></svg>
            </div>
            <ul tabIndex={0} className="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
              <Link href="/">
                <li><a>Welcome</a></li>
              </Link>
            </ul>
          </div>
        </div>      
        <div className="navbar-center">
          <div className="badge badge-secondary badge-outline">Decentralized Stablecoin dUSD</div>
        </div>
        <div className="navbar-end">
          <div className="flex-none">
            <WalletConnect />
          </div>
        </div>
      </div>

      <div className="hero min-h-screen" style={{backgroundImage: 'url(https://img.daisyui.com/images/stock/photo-1507358522600-9f71e620c44e.jpg)'}}>
        <div className="hero-overlay bg-opacity-60"></div>
        <div className="hero-content text-center text-neutral-content">
          <div className="">
            <h1 className="max-w-lg mb-5 text-5xl font-bold">Decentralized Stablecoin dUSD</h1>
            <p className="max-w-lg mb-5">Welcome to the new era of finance. Mint and start trading your decentralized stablecoin.</p>
            <div className="min-w-min">
              {!lucid ? (
                  <div className="mb-5">
                    <div role="alert" className="alert alert-warning">
                    <svg xmlns="http://www.w3.org/2000/svg" className="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                    <span>Please connect your wallet!</span>
                    </div>
                  </div>
                ) : (
                  <Link href="/helios">
                    <button className="btn btn-primary">Launch App</button>
                  </Link>
                )}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Home
